name: Build MAUI-Windows

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
    DOTNETVERSION:  6.0.200-preview.22055.15
    MAUIROLLBACKLINK: https://aka.ms/dotnet/maui/preview.12.json

jobs:
  buildwindows:
    runs-on: windows-2022
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK ${{env.DOTNETVERSION}}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '${{env.DOTNETVERSION}}'

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-prerelease: true

      - name: Install .NET MAUI
        shell: pwsh
        run: |
          & dotnet --version
          & dotnet nuget locals all --clear
          & dotnet workload install maui --from-rollback-file ${{env.MAUIROLLBACKLINK}} --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
          & dotnet workload install android ios maccatalyst tvos macos maui wasm-tools --from-rollback-file ${{env.MAUIROLLBACKLINK}} --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
            
      - name: Restore nuget packages
        run: dotnet restore src\WeatherTwentyOne.sln

      - name: Build Weather21
        shell: pwsh
        run: dotnet build src/WeatherTwentyOne -f net6.0-android -c Debug

      - name: Build WinUI3 Debug
        run: msbuild src\WeatherTwentyOne.sln -restore -p:Configuration=Debug

      - name: Build WinUI3 Release
        run: msbuild src\WeatherTwentyOne.sln -p:Configuration=Release

      - uses: actions/upload-artifact@v2
        with:
          name: artifacts-windows
          path: |
            src\WeatherTwentyOne\bin\Debug\**\*-Signed.apk
